package bill;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Billing extends javax.swing.JFrame {

    public Billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CustomerRef = new javax.swing.JLabel();
        MobileNo = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        PostCode = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        IDNumber = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        CustomerReftxt = new javax.swing.JTextField();
        FirstNametxt = new javax.swing.JTextField();
        Surnametxt = new javax.swing.JTextField();
        Addresstxt = new javax.swing.JTextField();
        PostCodetxt = new javax.swing.JTextField();
        Mobiletxt = new javax.swing.JTextField();
        Emailtxt = new javax.swing.JTextField();
        IDtxt = new javax.swing.JTextField();
        Gendercombo = new javax.swing.JComboBox<>();
        IDcombo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        Bread = new javax.swing.JRadioButton();
        Fruits = new javax.swing.JRadioButton();
        Washingsoap = new javax.swing.JRadioButton();
        Washingpowder = new javax.swing.JRadioButton();
        Bathingsoap = new javax.swing.JRadioButton();
        Electronics = new javax.swing.JRadioButton();
        Furniture = new javax.swing.JRadioButton();
        Books = new javax.swing.JRadioButton();
        Clothes = new javax.swing.JRadioButton();
        Vegetables = new javax.swing.JRadioButton();
        Breadtxt = new javax.swing.JTextField();
        Fruitstxt = new javax.swing.JTextField();
        Washingsoaptxt = new javax.swing.JTextField();
        Washingpowdertxt = new javax.swing.JTextField();
        Bathingsoaptxt = new javax.swing.JTextField();
        Electronicstxt = new javax.swing.JTextField();
        Furnituretxt = new javax.swing.JTextField();
        Bookstxt = new javax.swing.JTextField();
        Clothestxt = new javax.swing.JTextField();
        Vegetablestxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Tax = new javax.swing.JLabel();
        Subtotal = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        Taxtxt = new javax.swing.JTextField();
        Subtotaltxt = new javax.swing.JTextField();
        Totaltxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnreset = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btntotal = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        invoicetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BILLING/INVOICE");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CustomerRef.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        CustomerRef.setText("Customer Ref");

        MobileNo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        MobileNo.setText("Mobile");

        Email.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Email.setText("Email");

        PostCode.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PostCode.setText("Post Code");

        Address.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Address.setText("Address");

        Surname.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Surname.setText("Surname");

        FirstName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        FirstName.setText("First Name");

        IDNumber.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        IDNumber.setText("ID Number");

        Gender.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Gender.setText("Gender");

        ID.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        ID.setText("Type Of ID");

        Gendercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        IDcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerRef, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerReftxt)
                    .addComponent(FirstNametxt)
                    .addComponent(Surnametxt)
                    .addComponent(Addresstxt)
                    .addComponent(PostCodetxt)
                    .addComponent(Mobiletxt)
                    .addComponent(Emailtxt)
                    .addComponent(IDtxt)
                    .addComponent(Gendercombo, 0, 109, Short.MAX_VALUE)
                    .addComponent(IDcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerRef)
                    .addComponent(CustomerReftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirstNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Surname)
                    .addComponent(Surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(Addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PostCode)
                    .addComponent(PostCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileNo)
                    .addComponent(Mobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(Emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDNumber)
                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender)
                    .addComponent(Gendercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(IDcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Bread.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bread.setText("Bread");

        Fruits.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Fruits.setText("Fruits");

        Washingsoap.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Washingsoap.setText("Washing Soap");

        Washingpowder.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Washingpowder.setText("Washing Powder");

        Bathingsoap.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Bathingsoap.setText("Bathing Soap");

        Electronics.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Electronics.setText("Electronics");

        Furniture.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Furniture.setText("Furniture");

        Books.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Books.setText("Books");

        Clothes.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Clothes.setText("Clothes");

        Vegetables.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Vegetables.setText("Vegetables");

        Breadtxt.setText("0");

        Fruitstxt.setText("0");

        Washingsoaptxt.setText("0");

        Washingpowdertxt.setText("0");
        Washingpowdertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WashingpowdertxtActionPerformed(evt);
            }
        });

        Bathingsoaptxt.setText("0");

        Electronicstxt.setText("0");

        Furnituretxt.setText("0");

        Bookstxt.setText("0");

        Clothestxt.setText("0");

        Vegetablestxt.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Vegetables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Washingpowder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bathingsoap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Electronics, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Clothes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Books, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Furniture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Washingsoap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fruits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bread, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Breadtxt)
                    .addComponent(Fruitstxt)
                    .addComponent(Washingsoaptxt)
                    .addComponent(Washingpowdertxt)
                    .addComponent(Bathingsoaptxt)
                    .addComponent(Electronicstxt)
                    .addComponent(Furnituretxt)
                    .addComponent(Bookstxt)
                    .addComponent(Clothestxt)
                    .addComponent(Vegetablestxt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bread)
                    .addComponent(Breadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fruits)
                    .addComponent(Fruitstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Washingsoap)
                    .addComponent(Washingsoaptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Washingpowder)
                    .addComponent(Washingpowdertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bathingsoap)
                    .addComponent(Bathingsoaptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Electronics)
                    .addComponent(Electronicstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Furniture)
                    .addComponent(Furnituretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Books)
                    .addComponent(Bookstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clothes)
                    .addComponent(Clothestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vegetables)
                    .addComponent(Vegetablestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Tax.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Tax.setText("Tax");

        Subtotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Subtotal.setText("Sub Total");

        total.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        total.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Taxtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(Subtotaltxt)
                    .addComponent(Totaltxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tax)
                    .addComponent(Taxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtotal)
                    .addComponent(Subtotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(Totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnreset.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btntotal.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        btnprint.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoicetxt))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(invoicetxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    double iTotal, iSubtotal, iTax; 
    private void WashingpowdertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WashingpowdertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WashingpowdertxtActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try{
            invoicetxt.print();
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        JFrame frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Customer Billing System", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        
        FirstNametxt.setText(" ");
        Surnametxt.setText(" ");
        Addresstxt.setText(" ");
        PostCodetxt.setText(" ");
        Mobiletxt.setText(" ");
        Emailtxt.setText(" ");
        IDtxt.setText(" ");
        
        Taxtxt.setText(" ");
        Subtotaltxt.setText(" ");
        Totaltxt.setText(" ");
        
        Breadtxt.setText("0");
        Fruitstxt.setText("0");
        Washingsoaptxt.setText("0");
        Washingpowdertxt.setText("0");
        Bathingsoaptxt.setText("0");
        Electronicstxt.setText("0");
        Furnituretxt.setText("0");
        Bookstxt.setText("0");
        Clothestxt.setText("0");
        Vegetablestxt.setText("0");
        
        Bread.setSelected(false);
        Fruits.setSelected(false);
        Washingsoap.setSelected(false);
        Washingpowder.setSelected(false);
        Bathingsoap.setSelected(false);
        Electronics.setSelected(false);
        Furniture.setSelected(false);
        Books.setSelected(false);
        Clothes.setSelected(false);
        Vegetables.setSelected(false);
        
        Gendercombo.setSelectedIndex(0);
        IDcombo.setSelectedIndex(0);
        
        invoicetxt.setText(null);
        
        CustomerReftxt.setText(null);
        CustomerReftxt.setEnabled(false);
        int refs = 5015 + (int)(Math.random()*17238);
        String cRef = "";
        cRef += refs + 1580;
        CustomerReftxt.setText(cRef);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        double itemcost0 = Double.parseDouble(Breadtxt.getText())*50;
        double itemcost1 = Double.parseDouble(Fruitstxt.getText())*100;
        double itemcost2 = Double.parseDouble(Washingsoaptxt.getText())*80;
        double itemcost3 = Double.parseDouble(Washingpowdertxt.getText())*50;
        double itemcost4 = Double.parseDouble(Bathingsoaptxt.getText())*30;
        double itemcost5 = Double.parseDouble(Electronicstxt.getText())*2000;
        double itemcost6 = Double.parseDouble(Furnituretxt.getText())*1000;
        double itemcost7 = Double.parseDouble(Bookstxt.getText())*100;
        double itemcost8 = Double.parseDouble(Clothestxt.getText())*500;
        double itemcost9 = Double.parseDouble(Vegetablestxt.getText())*100;
        
        double itemcost10 = itemcost0+itemcost1+itemcost2+itemcost3+itemcost4+itemcost5+itemcost6+itemcost7+itemcost8+itemcost9;
        
        iTax = itemcost10/1000;
        iSubtotal = itemcost10;
        iTotal = iSubtotal + iTax;
        
        String tax = "Ksh " + Double.toString(iTax);
        String Subtotal = "Ksh " + Double.toString(iSubtotal);
        String Total = "Ksh " + Double.toString(iTotal);
        
        Taxtxt.setText(tax);
        Subtotaltxt.setText(Subtotal);
        Totaltxt.setText(Total);
        
        int refs = 1325 + (int)(Math.random()*3456);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
        tDate.format(timer.getTime());
        
        //invoicetxt.setEnabled(true);
 
        String a = "\tBilling\n" +
        "Reference:\t\t\t"+refs+
         "\n===================================================================\t"+
                
                "\n====================================================================\t"+
                "\nCustomer Ref:\t\t\t"+CustomerRef.getText()+
                "\nFirst Name:\t\t\t"+FirstNametxt.getText()+
                "\nSurname:\t\t\t"+Surnametxt.getText()+
                "\nBread:\t\t\t"+Breadtxt.getText()+
                "\nFruits:\t\t\t"+Fruitstxt.getText()+
                "\nWashing Soap:\t\t\t"+Washingsoaptxt.getText()+
                "\nWashing Powder:\t\t\t"+Washingpowdertxt.getText()+
                "\nBathing Soap:\t\t\t"+Bathingsoaptxt.getText()+
                "\nElectronics:\t\t\t"+Electronicstxt.getText()+
                "\nFurniture:\t\t\t"+Furnituretxt.getText()+
                "\nBooks:\t\t\t"+Bookstxt.getText()+
                "\nClothes:\t\t\t"+Clothestxt.getText()+
                "\nVegetables:\t\t\t"+Vegetablestxt.getText()+
                "\n====================================================================\t"+
                
                "\nTax:\t\t\t"+iTax +
                "\nSub Total:\t\t\t"+iSubtotal +
                "\nTotal:\t\t\t"+iTotal +
                "\n====================================================================\t"+
                "\nDate: "+tDate.format(timer.getTime())+
                         "\t\tTime: "+tTime.format(timer.getTime())+
                
                "\n\n\tThank you for shopping at iSupermarket";
        invoicetxt.setText(a);
    }//GEN-LAST:event_btntotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField Addresstxt;
    private javax.swing.JRadioButton Bathingsoap;
    private javax.swing.JTextField Bathingsoaptxt;
    private javax.swing.JRadioButton Books;
    private javax.swing.JTextField Bookstxt;
    private javax.swing.JRadioButton Bread;
    private javax.swing.JTextField Breadtxt;
    private javax.swing.JRadioButton Clothes;
    private javax.swing.JTextField Clothestxt;
    private javax.swing.JLabel CustomerRef;
    private javax.swing.JTextField CustomerReftxt;
    private javax.swing.JRadioButton Electronics;
    private javax.swing.JTextField Electronicstxt;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNametxt;
    private javax.swing.JRadioButton Fruits;
    private javax.swing.JTextField Fruitstxt;
    private javax.swing.JRadioButton Furniture;
    private javax.swing.JTextField Furnituretxt;
    private javax.swing.JLabel Gender;
    private javax.swing.JComboBox<String> Gendercombo;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDNumber;
    private javax.swing.JComboBox<String> IDcombo;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JLabel MobileNo;
    private javax.swing.JTextField Mobiletxt;
    private javax.swing.JLabel PostCode;
    private javax.swing.JTextField PostCodetxt;
    private javax.swing.JLabel Subtotal;
    private javax.swing.JTextField Subtotaltxt;
    private javax.swing.JLabel Surname;
    private javax.swing.JTextField Surnametxt;
    private javax.swing.JLabel Tax;
    private javax.swing.JTextField Taxtxt;
    private javax.swing.JTextField Totaltxt;
    private javax.swing.JRadioButton Vegetables;
    private javax.swing.JTextField Vegetablestxt;
    private javax.swing.JRadioButton Washingpowder;
    private javax.swing.JTextField Washingpowdertxt;
    private javax.swing.JRadioButton Washingsoap;
    private javax.swing.JTextField Washingsoaptxt;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntotal;
    private javax.swing.JTextField invoicetxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
